modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="bruhers"
version="1.0.0"
displayName="bruhers"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="konzo, MCreator"

[[dependencies.bruhers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




